// ═══════════════════════════════════════════════════════════════
// DESCRIPTION TEMPLATES
// Markdown/Wiki formatters for Jira descriptions
// ═══════════════════════════════════════════════════════════════

import type { ContentLevel, NormalizedItem, JiraPreset } from "./types";
import { getPreset } from "./presets";

// ─────────────────────────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────────────────────────

function parseJsonArray(jsonString: string | null | undefined): string[] {
  if (!jsonString) return [];
  try {
    const parsed = JSON.parse(jsonString);
    return Array.isArray(parsed) ? parsed : [jsonString];
  } catch {
    return jsonString ? [jsonString] : [];
  }
}

function formatNumberedList(items: string[]): string {
  return items.map((item, i) => `${i + 1}. ${item}`).join("\n");
}

function formatBulletList(items: string[]): string {
  return items.map((item) => `* ${item}`).join("\n");
}

// ─────────────────────────────────────────────────────────────────
// Compact Templates
// ─────────────────────────────────────────────────────────────────

function formatCompactEpic(item: NormalizedItem): string {
  const parts: string[] = [];

  if (item.description) {
    parts.push(item.description);
  }

  if (item.businessValue) {
    parts.push(`\n**Business Value:** ${item.businessValue}`);
  }

  return parts.join("\n").trim();
}

function formatCompactStory(item: NormalizedItem): string {
  const parts: string[] = [];

  if (item.userStory) {
    parts.push(item.userStory);
  }

  const criteria = parseJsonArray(item.acceptanceCriteria);
  if (criteria.length > 0) {
    parts.push(`\n**Acceptance Criteria:**\n${formatNumberedList(criteria)}`);
  }

  return parts.join("\n").trim();
}

function formatCompactSubtask(item: NormalizedItem): string {
  return item.description || "";
}

// ─────────────────────────────────────────────────────────────────
// Full Templates
// ─────────────────────────────────────────────────────────────────

function formatFullEpic(item: NormalizedItem): string {
  const parts: string[] = [];

  if (item.description) {
    parts.push("## Overview");
    parts.push(item.description);
  }

  if (item.businessValue) {
    parts.push("\n## Business Value");
    parts.push(item.businessValue);
  }

  const criteria = parseJsonArray(item.acceptanceCriteria);
  if (criteria.length > 0) {
    parts.push("\n## Acceptance Criteria");
    parts.push(formatNumberedList(criteria));
  }

  const deps = parseJsonArray(item.dependencies);
  if (deps.length > 0) {
    parts.push("\n## Dependencies");
    parts.push(formatBulletList(deps));
  }

  parts.push("\n---");
  parts.push(`*Generated by Requirements Foundry • ${item.code}*`);

  return parts.join("\n").trim();
}

function formatFullStory(item: NormalizedItem): string {
  const parts: string[] = [];

  if (item.userStory) {
    parts.push("## User Story");
    parts.push(item.userStory);
  }

  if (item.persona) {
    parts.push("\n## Persona");
    parts.push(item.persona);
  }

  const criteria = parseJsonArray(item.acceptanceCriteria);
  if (criteria.length > 0) {
    parts.push("\n## Acceptance Criteria");
    parts.push(formatNumberedList(criteria));
  }

  if (item.technicalNotes) {
    parts.push("\n## Technical Notes");
    parts.push(item.technicalNotes);
  }

  parts.push("\n---");
  const code = item.epicCode ? `${item.epicCode}/${item.code}` : item.code;
  parts.push(`*Generated by Requirements Foundry • ${code}*`);

  return parts.join("\n").trim();
}

function formatFullSubtask(item: NormalizedItem): string {
  const parts: string[] = [];

  if (item.description) {
    parts.push(item.description);
  }

  if (item.effort) {
    parts.push("\n## Effort Estimate");
    parts.push(item.effort);
  }

  parts.push("\n---");
  const code = item.epicCode && item.storyCode
    ? `${item.epicCode}/${item.storyCode}/${item.code}`
    : item.code;
  parts.push(`*Generated by Requirements Foundry • ${code}*`);

  return parts.join("\n").trim();
}

// ─────────────────────────────────────────────────────────────────
// Wiki Markup Converter (for Server/DC)
// ─────────────────────────────────────────────────────────────────

export function markdownToWiki(md: string): string {
  return md
    // Headers
    .replace(/^## (.+)$/gm, "h2. $1")
    .replace(/^### (.+)$/gm, "h3. $1")
    // Bold
    .replace(/\*\*(.+?)\*\*/g, "*$1*")
    // Bullet lists (preserve)
    .replace(/^\* (.+)$/gm, "* $1")
    // Numbered lists
    .replace(/^\d+\. (.+)$/gm, "# $1")
    // Horizontal rule
    .replace(/^---$/gm, "----")
    // Italic (markdown style)
    .replace(/_(.+?)_/g, "_$1_");
}

// ─────────────────────────────────────────────────────────────────
// Main Export Functions
// ─────────────────────────────────────────────────────────────────

export function formatDescription(
  item: NormalizedItem,
  level: ContentLevel,
  preset: JiraPreset
): string {
  let description: string;

  // Generate markdown description based on item type and content level
  switch (item.issueType) {
    case "Epic":
      description = level === "compact"
        ? formatCompactEpic(item)
        : formatFullEpic(item);
      break;
    case "Story":
      description = level === "compact"
        ? formatCompactStory(item)
        : formatFullStory(item);
      break;
    case "Sub-task":
      description = level === "compact"
        ? formatCompactSubtask(item)
        : formatFullSubtask(item);
      break;
    default:
      description = item.description || "";
  }

  // Convert to wiki markup for Server/DC
  const presetConfig = getPreset(preset);
  if (!presetConfig.supportsMarkdown && description) {
    description = markdownToWiki(description);
  }

  return description;
}

export function formatEpicDescription(
  item: NormalizedItem,
  level: ContentLevel
): string {
  return level === "compact" ? formatCompactEpic(item) : formatFullEpic(item);
}

export function formatStoryDescription(
  item: NormalizedItem,
  level: ContentLevel
): string {
  return level === "compact" ? formatCompactStory(item) : formatFullStory(item);
}

export function formatSubtaskDescription(
  item: NormalizedItem,
  level: ContentLevel
): string {
  return level === "compact" ? formatCompactSubtask(item) : formatFullSubtask(item);
}
