// ═══════════════════════════════════════════════════════════════
// INSTRUCTIONS GENERATOR
// Generates import-instructions.md for the export bundle
// ═══════════════════════════════════════════════════════════════

import type { ExportStats, JiraPreset, ExportConfig } from "./types";
import { getPreset } from "./presets";

// ─────────────────────────────────────────────────────────────────
// Main Generator
// ─────────────────────────────────────────────────────────────────

export function generateInstructions(
  projectName: string,
  config: ExportConfig,
  stats: ExportStats,
  generatedAt: string
): string {
  const presetConfig = getPreset(config.preset);

  return `# Jira Import Instructions

## Export Summary

| Metric | Value |
|--------|-------|
| **Project** | ${projectName} |
| **Export Date** | ${formatDate(generatedAt)} |
| **Jira Target** | ${presetConfig.displayName} |
| **Content Level** | ${config.contentLevel === "full" ? "Full (with all details)" : "Compact"} |
| **Include Subtasks** | ${config.includeSubtasks ? "Yes" : "No"} |

### Item Counts

| Type | Count |
|------|-------|
| Epics | ${stats.epicCount} |
| Stories | ${stats.storyCount} |
| Subtasks | ${stats.subtaskCount} |
| **Total Rows** | **${stats.totalRows}** |

---

## How to Import into Jira

### Step 1: Access the CSV Importer

${getImportAccessInstructions(config.preset)}

### Step 2: Upload the CSV File

1. Click **"Choose File"** and select \`jira-import.csv\`
2. Jira will preview the first few rows
3. Verify the columns are detected correctly

### Step 3: Configure Field Mapping

Most fields should auto-map. Verify these mappings:

| CSV Column | Jira Field |
|------------|------------|
| Issue ID | Issue ID (for import) |
| Parent ID | Parent ID |
| Issue Type | Issue Type |
| Summary | Summary |
| Description | Description |
| Priority | Priority |
${presetConfig.supportsLabels ? "| Labels | Labels |" : ""}
${presetConfig.storyPointsField ? `| ${presetConfig.storyPointsField} | Story Points |` : ""}

### Step 4: Import Settings

${getImportSettingsInstructions(config.preset)}

### Step 5: Review and Import

1. Click **"Begin Import"**
2. Review the import summary
3. Check for any validation errors
4. Click **"Import"** to proceed

---

## Hierarchy Structure

This export uses **Issue ID** and **Parent ID** columns to establish hierarchy:

\`\`\`
Epic (TEMP-E-001)
├── Story (TEMP-S-001) → Parent: TEMP-E-001
│   ├── Sub-task (TEMP-ST-001) → Parent: TEMP-S-001
│   └── Sub-task (TEMP-ST-002) → Parent: TEMP-S-001
└── Story (TEMP-S-002) → Parent: TEMP-E-001
\`\`\`

Jira will automatically:
- Create real issue keys (e.g., PROJ-1, PROJ-2)
- Link children to their parents
- Preserve the hierarchy structure

---

## Troubleshooting

### Common Issues

**"Invalid Issue Type"**
- Ensure your Jira project has Epic, Story, and ${presetConfig.subtaskIssueType} issue types
- Check that issue types are enabled in your project settings

**"Parent not found"**
- This usually means the import order was changed
- Re-import without sorting or filtering the CSV

**"Field not found"**
${presetConfig.storyPointsField === "Custom field (Story Points)"
  ? "- For Server/DC: Create a custom field named 'Story Points' if it doesn't exist"
  : "- Story Points field may need to be enabled in your project"}

**Large imports timing out**
- For ${stats.totalRows > 500 ? "your large export" : "large exports"}, consider:
  - Importing during off-peak hours
  - Splitting into smaller batches by epic

---

## File Contents

| File | Description |
|------|-------------|
| \`jira-import.csv\` | Main import file for Jira |
| \`import-instructions.md\` | This file |
| \`raw-data.json\` | Original data (for backup/debugging) |

---

*Generated by Requirements Foundry*
*${formatDate(generatedAt)}*
`;
}

// ─────────────────────────────────────────────────────────────────
// Helper Functions
// ─────────────────────────────────────────────────────────────────

function formatDate(isoString: string): string {
  const date = new Date(isoString);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function getImportAccessInstructions(preset: JiraPreset): string {
  switch (preset) {
    case "cloud-company":
    case "cloud-team":
      return `1. Go to your Jira project
2. Click **"Project Settings"** (gear icon)
3. Select **"System"** → **"External System Import"**
4. Choose **"CSV"** as the import source

Or use the direct URL:
\`https://your-domain.atlassian.net/secure/admin/ExternalImport1.jspa\``;

    case "server-dc":
      return `1. Go to your Jira instance
2. Navigate to **"System"** → **"Import & Export"** → **"External System Import"**
3. Select **"CSV"**

Or access via: \`/secure/admin/ExternalImport1.jspa\``;
  }
}

function getImportSettingsInstructions(preset: JiraPreset): string {
  const commonSettings = `- **Date format**: Leave as default (ISO format)
- **Map field value**: Create any missing values automatically`;

  switch (preset) {
    case "cloud-company":
      return `${commonSettings}
- **Use existing Issue IDs**: No (let Jira create new keys)`;

    case "cloud-team":
      return `${commonSettings}
- Team-managed projects have simplified import options
- Most settings can be left as default`;

    case "server-dc":
      return `${commonSettings}
- **Create users**: No (unless you want to auto-create)
- **Custom fields**: Map "Custom field (Story Points)" to your Story Points field`;
  }
}
